#! /bin/sh
if [ "$(xrandr | grep "DP-0 connected")" ]
then
    bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9 10
else
    bspc moniter -d 1 2 3 4 5 6 7 8 9 10
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
    bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
fi

# Used to make polybar maintain proper workspaces per monitor when going from 2
# to 1 monitor again.. This may include some monitor re-ordering issues
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config pointer_action1 move

# Sometimes when using an external monitor that is larger than the base laptop
# screen size, padding would be applied to make the nodes the size of the
# laptop resolution - we don't want that, as the nodes should fill out the
# entire height/width of the monitor, so we set all padding to 0.
bspc config top_padding 22
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc config active_border_color "#263238"
bspc config focused_border_color "#00BCD4"


bspc config border_width       1
bspc config border_radius     6 
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "kitty" desktop=^1 follow=off
bspc rule -a "firefox" desktop=^2
bspc rule -a "code-oss" desktop=^3
bspc rule -a "Spotify" desktop=^4
bspc rule -a "Thunar" desktop=^5 focus=off
bspc rule -a "discord" desktop=^6 focus=off

# Xinput configs (touchpad)
xinput set-prop "MSFT0002:00 04F3:304B Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "MSFT0002:00 04F3:304B Touchpad" "libinput Click Method Enabled" 0 1
xinput set-prop "MSFT0002:00 04F3:304B Touchpad" "libinput Disable While Typing Enabled" 0
xinput -disable 'AT Translated Set 2 keyboard'
xinput set-prop "Logitech Gaming Mouse G402" "libinput Accel Profile Enabled" 0 1 0

xsetroot -cursor_name left_ptr
nitrogen --restore
sh ~/.config/bspwm/autostart.sh
